name: ci-workflow-test
on:
  pull_request:
    branches:
      - develop
jobs:
  # nome que você dá pro job
  check-application:
    runs-on: ubuntu-latest
  # tiramos strategy pra não deixar pesado
    steps:
      # pega o que acabou de subir e adiciona nessa máquina ubuntu (git checkout)
      # actions/ é um repositório do gh chamado actions, estamos usando setups do gh nesse caso
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          #aqui deixou de ser array de versões e passou a ser uma única
          node-version: 18
      # name é uma pequena descrição, pode ou não usar
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        # id serve pra pegar uma action e usar em outro step
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: aquijuz/teste-ci:latest
      - run: npm test
      - run: npm start
