name: ci-workflow-test
on: [push]
jobs:
  # nome que você dá pro job
  check-application:
    runs-on: ubuntu-latest
    steps:
      # pega o que acabou de subir e adiciona nessa máquina ubuntu (git checkout)
      # actions/ é um repositório do gh chamado actions, estamos usando setups do gh nesse caso
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm test
      - run: npm start
